import{test,expect}from'@playwright/test';import{createRequire}from'node:module';import{readFileSync}from'node:fs';const require=createRequire(import.meta.url);const{buildSync}=createRequire(require.resolve('tsx'))('esbuild');
const bundle=buildSync({stdin:{contents:`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{TaskScreen}from'./app/task-screen';function App(){const[later,setLater]=useState(false);window.addLater=()=>setLater(true);return <div className="wd"><TaskScreen title="Trip" conversationId="trip" kind="doc" state="live" statusLabel="Working" onBack={()=>{}} items={[{id:'before',kind:'agent',text:'Checking routes.',createdAt:'2026-10-02T12:00:00Z'},{id:'block1',kind:'blocks',createdAt:'2026-10-02T12:00:05Z',blocks:[{type:'text',style:'heading',text:'Initial itinerary'}],followUpActions:[]},...(later?[{id:'after',kind:'agent',text:'Hotel research is complete.',createdAt:'2026-10-02T12:00:10Z'},{id:'block2',kind:'blocks',createdAt:'2026-10-02T12:00:15Z',blocks:[{type:'text',style:'heading',text:'Hotel shortlist'}],followUpActions:[]}]:[])]}/></div>}createRoot(document.getElementById('root')).render(<App/>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',define:{'process.env.NODE_ENV':'"development"'}}).outputFiles[0].text;
test('later replies and block groups preserve the earlier block position',async({page})=>{
 await page.route('**/block-order-preview',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));await page.goto('/block-order-preview');for(const f of ['app/brand-tokens.css','app/wdyt.css'])await page.addStyleTag({content:readFileSync(f,'utf8')});await page.addScriptTag({content:bundle});
 await expect(page.getByText('Initial itinerary',{exact:true})).toBeVisible();
 await expect(page.locator('.wd-reactable').first()).toHaveClass(/has-following/);
 await expect(page.locator('.wd-block-message').first()).toHaveClass(/is-grouped/);
 expect(await page.locator('.wd-reactable .wd-agent').first().evaluate(el=>getComputedStyle(el,'::before').display)).toBe('none');
 const bubble=await page.locator('.wd-reactable').first().boundingBox(),block=await page.locator('.wd-block-message').first().boundingBox();expect(block!.y-bubble!.y-bubble!.height).toBeCloseTo(4,0);
 await page.evaluate(()=>{(window as any).addLater()});
 const transcript=await page.locator('.wd-thread').innerText();expect(transcript.indexOf('Initial itinerary')).toBeLessThan(transcript.indexOf('Hotel research is complete.'));expect(transcript.indexOf('Hotel research is complete.')).toBeLessThan(transcript.indexOf('Hotel shortlist'));await expect(page.getByText('Initial itinerary',{exact:true})).toHaveCount(1);
 expect(await page.locator('.wd-block-message').first().evaluate(el=>getComputedStyle(el,'::before').display)).toBe('none');
 expect(await page.locator('.wd-block-message').last().evaluate(el=>getComputedStyle(el,'::before').content)).not.toBe('none');
});
