import{test,expect}from'@playwright/test';import{createRequire}from'node:module';import{applyConversationAction,type ConversationSettings}from'../../lib/conversation-settings';
const require=createRequire(import.meta.url);const{buildSync}=createRequire(require.resolve('tsx'))('esbuild');
const bundle=buildSync({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{ResultBlocks}from'./app/result-blocks';import{ConversationDetailsContext}from'./app/conversation-details-context';import{useConversationSettings}from'./app/conversation-settings';function App(){const s=useConversationSettings('test@example.invalid',false);return s.ready?<ConversationDetailsContext.Provider value={{setting:s.settings['run:test'],save:a=>s.apply({...a,key:'run:test'})}}><ResultBlocks resultId="test:blocks" blocks={[{type:'checklist',title:'Before you go',items:[{text:'Book hotel',done:false},{text:'Pack bag',done:true}]}]}/></ConversationDetailsContext.Provider>:null;}createRoot(document.getElementById('root')).render(<App/>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,write:false,format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"development"'}}).outputFiles[0].text;
test('checklist checks and unchecks survive reload; failed saves restore previous state',async({page})=>{
 let settings:ConversationSettings={};let fail=false;
 await page.route('**/checklist-preview',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div><script>'+bundle.replaceAll('</script','<\\/script')+'</script>'}));
 await page.route('**/api/conversations',async r=>{if(r.request().method()==='PATCH'){if(fail)return r.fulfill({status:503,json:{error:'Save failed'}});settings=applyConversationAction(settings,r.request().postDataJSON());}return r.fulfill({json:{settings,messages:{}}});});
 await page.goto('/checklist-preview');const hotel=page.getByRole('checkbox',{name:'Book hotel'});await hotel.click();await expect(hotel).toHaveAttribute('aria-checked','true');await expect(hotel).toBeEnabled();
 await page.reload();await expect(hotel).toHaveAttribute('aria-checked','true');await hotel.click();await expect(hotel).toBeEnabled();await page.reload();await expect(hotel).toHaveAttribute('aria-checked','false');
 fail=true;await hotel.click();await expect(page.getByRole('alert')).toBeVisible();await expect(hotel).toHaveAttribute('aria-checked','false');
});
