import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {buildSync}=createRequire(require.resolve('tsx'))('esbuild');
const bundle=buildSync({entryPoints:['tests/browser/fixtures/connector-accounts.tsx'],bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',define:{'process.env.NODE_ENV':'"development"'}}).outputFiles[0].text;
test('connected accounts start collapsed, expand in place and keep add-account independent',async({page})=>{
 await page.route('**/connector-accounts-fixture',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));
 await page.route('**/api/connections/composio**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({configured:true,items:[{slug:'twitter',name:'Twitter',connected:true,noAuth:false,accounts:[{id:'active',label:'Connected account',status:'ACTIVE'}]}],cursor:null})}));
 await page.goto('/connector-accounts-fixture');
 for(const path of ['app/brand-tokens.css','app/wdyt.css'])await page.addStyleTag({content:readFileSync(path,'utf8')});
 await page.addScriptTag({content:bundle});
 const toggle=page.getByRole('button',{name:'X 1 account',exact:true});
 await expect(toggle).toHaveAttribute('aria-expanded','false');
 await expect(page.locator('.wd-connector-accounts')).toHaveAttribute('inert','');
 expect(await page.locator('.wd-connector-accounts').evaluate(el=>el.getBoundingClientRect().height)).toBe(0);
 const before=await toggle.boundingBox();
 await page.screenshot({path:'/tmp/dash-connectors-collapsed.png'});
 await toggle.click();
 await expect(toggle).toHaveAttribute('aria-expanded','true');
 await expect(page.getByRole('button',{name:'Disconnect X Connected account'})).toBeVisible();
 await expect.poll(()=>page.locator('.wd-connector-accounts').evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(20);
 expect(await toggle.boundingBox()).toEqual(before);
 await page.screenshot({path:'/tmp/dash-connectors-expanded.png'});
 await toggle.click();
 await expect(toggle).toHaveAttribute('aria-expanded','false');
 await expect(page.getByRole('button',{name:'Add account'})).toBeHidden();
 await toggle.click();
 await page.getByRole('button',{name:'Add account'}).click();
 await expect(toggle).toHaveAttribute('aria-expanded','true');
});
