import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {buildSync}=createRequire(require.resolve('tsx'))('esbuild');
const bundle=buildSync({entryPoints:['tests/browser/fixtures/pending-interaction.tsx'],bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',define:{'process.env.NODE_ENV':'"development"'}}).outputFiles[0].text;
test('pending input collapses before delivery, restores on failure, and never collapses a new request',async({page})=>{
 await page.route('**/pending-fixture',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));
 await page.route('**/api/**',r=>r.fulfill({json:{items:[]}}));
 await page.goto('/pending-fixture');
 for(const path of ['app/brand-tokens.css','app/wdyt.css'])await page.addStyleTag({content:readFileSync(path,'utf8')});
 await page.addScriptTag({content:bundle});
 const card=page.locator('[data-inline-id="approval:first"]');
 await expect(card).toContainText('Which side?');
 await page.locator('textarea').last().fill('No thanks');
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect(card).toContainText('Declined');
 await expect(card.locator('.wd-inline-panel-ghost')).toHaveCount(0);
 await expect(card.getByText('Which side?')).toHaveCount(0);
 await page.evaluate(()=>(window as any).finishSend(false));
 await expect(card).toContainText('Which side?');
 await page.locator('textarea').last().fill('Try something else');
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect(card).toContainText('Declined');
 await page.evaluate(()=>(window as any).finishSend(true));
 await expect(card).toContainText('Declined');
 await page.evaluate(()=>(window as any).nextRequest());
 await expect(page.locator('[data-inline-id="approval:second"]')).toContainText('Which side?');
});
