import {test,expect} from '@playwright/test';
test('one connections page puts Apple first and searches built-in and catalog apps together',async({page})=>{
 await page.goto('/?uiPreview=1');
 await page.getByRole('button',{name:'You',exact:true}).click();
 await page.getByRole('button',{name:'Connected apps',exact:true}).last().click();
 const screen=page.locator('.wd-sources-page');
 await expect(screen).toHaveCount(1);
 await expect(page.getByRole('button',{name:'More connectors',exact:true})).toHaveCount(0);
 await expect(screen.getByRole('searchbox',{name:'Search apps'})).toHaveCount(1);
 await expect(screen.locator('.wd-settings-intro h2')).toHaveText('Connected apps.');
 await expect(screen.locator('.wd-settings-intro p')).toHaveText('Choose what Dash can use.');
 await expect(screen.locator('.wd-settings-intro h2')).toHaveCSS('font-size','26px');
 await expect(screen.locator('.wd-apple-sources').getByRole('heading').first()).toHaveText('Apple');
 await expect(screen.locator('.wd-settings-intro h2')).toBeInViewport();
 await expect.poll(() => screen.evaluate(el => { let node: Element | null = el; let count = 0; while (node) { count += node.getAnimations().filter(animation => animation.playState === 'running').length; node = node.parentElement; } return count; })).toBe(0);
 await page.screenshot({path:'/tmp/dash-connected-apps-button-12px.png'});
 expect(await screen.locator('.wd-apple-sources').evaluate(el=>el.compareDocumentPosition(document.querySelector('.wd-google-connectors')!) & Node.DOCUMENT_POSITION_FOLLOWING)).toBeTruthy();
 await expect(screen.locator('details[open]')).toHaveCount(0);
 await screen.getByRole('searchbox',{name:'Search apps'}).fill('photos');
 await expect(screen.locator('.wd-apple-sources .wd-source-summary strong')).toHaveText(['Photos']);
 await expect(screen.locator('.wd-google-connectors')).toHaveCount(0);
 await screen.getByRole('searchbox',{name:'Search apps'}).fill('canva');
 await expect(screen.getByRole('button',{name:/^Canva/})).toBeVisible();
 await expect(screen.locator('.wd-apple-sources')).toHaveCount(0);
 await screen.getByRole('searchbox',{name:'Search apps'}).fill('google');
 await expect(screen.locator('.wd-google-connectors')).toBeVisible();
 await screen.locator('.wd-google-connectors summary').click();
 await expect(screen.locator('.wd-google-connectors details')).toHaveAttribute('open','');
 await expect(screen).toHaveCount(1);
 await page.screenshot({path:'/tmp/dash-unified-connections-web.png'});
});
