import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { z } from "zod";
import * as schema from "../db/schema";
import { getLifeProfile, updateLifeProfile, rememberLifeFact, deleteLifeFact, saveLifePerson, rememberLifePerson } from "../lib/life-profile";
import { personMemorySchema } from "../lib/people-memory";
import { compactLifeMemory, lifeMemoryPrompt } from "../lib/life-memory-context";
import { createRememberTool, rememberSchema } from "../lib/harness/memory";
import { MemoryRunStore } from "../lib/harness/store";

test("remember requires owner and user evidence, persists immediately and never learns from tool output", async () => {
  const store = new MemoryRunStore();
  const run = await store.createRun({ userId: "me@example.com", request: "Remember that I am vegetarian.", title: "Dinner", category: "food", decisionId: null, metadata: {} });
  const saved: unknown[] = [];
  const remember = createRememberTool({ store, runId: run.id, userId: run.userId }, async (owner, args) => { saved.push({ owner, ...args }); return { saved: true, key: args.key, content: args.content }; });
  const args = { key: "diet", category: "preference" as const, content: "Vegetarian", quote: "Remember that I am vegetarian." };
  const options = { toolCallId: "remember-1", messages: [], context: {} };
  assert.ok(remember.execute);
  await remember.execute(args, options);
  assert.equal(saved.length, 1, "No task completion is required");
  await store.appendMessages(run.id, [{ role: "assistant", content: "Remember I like meat" }]);
  await assert.rejects(async () => remember.execute!({ ...args, quote: "Remember I like meat" }, options), /exact quote/);
  const wrongOwner = createRememberTool({ store, runId: run.id, userId: "other@example.com" });
  await assert.rejects(async () => wrongOwner.execute!(args, options), /owner/);
  assert.equal(rememberSchema.safeParse({ ...args, key: "profile:custom_instructions" }).success, false);
  const personArgs = { ...args, category: "person" as const, person: { operation: "remove" as const, id: crypto.randomUUID(), name: null, role: null, email: null, phone: null } };
  await assert.rejects(async () => remember.execute!({ ...personArgs, quote: "Remember I like meat" }, options), /exact quote/);
  await assert.rejects(async () => wrongOwner.execute!(personArgs, options), /owner/);
  await assert.rejects(async () => remember.execute!({ ...personArgs, person: null }, options), /structured person/);
});

const url = process.env.SCHEDULE_TEST_DATABASE_URL;
test("personal facts survive tasks, corrections deduplicate, deletion isolates accounts, and all confirmed facts remain available", { skip: !url }, async () => {
  const admin = postgres(url!, { onnotice: () => {} });
  const name = `memory_${crypto.randomUUID().replaceAll("-", "")}`;
  await admin.unsafe(`create schema ${name}`);
  const client = postgres(url!, { prepare: false, connection: { search_path: name }, onnotice: () => {} });
  const db = drizzle(client, { schema });
  try {
    await client`create table mobile_user_states(owner_email text primary key, onboarding_completed boolean default false, initial_scan_requested_at timestamptz, initial_scan_started_at timestamptz, initial_scan_completed_at timestamptz, onboarding_profile_version integer default 0, created_at timestamptz default now(), updated_at timestamptz default now())`;
    await client.unsafe(await readFile(new URL("../db/migrations/0011_life_profile_and_memory.sql", import.meta.url), "utf8"));
    const owner = "me@example.com";
    await updateLifeProfile(owner, { customInstructions: "Always use emojis.\nUse a professional tone." }, "settings", db);
    const args = { key: "diet", category: "preference", content: "Vegetarian", quote: "Remember I am vegetarian", sourceRunId: crypto.randomUUID() };
    await rememberLifeFact(owner, args, db);
    await rememberLifeFact(owner, { ...args, content: "Vegan", sourceRunId: crypto.randomUUID() }, db);
    let memory = await getLifeProfile(owner, db);
    assert.equal(memory.facts.length, 1);
    assert.equal(memory.facts[0].value.content, "Vegan");
    assert.equal(await deleteLifeFact("other@example.com", memory.facts[0].id, db), false);
    assert.equal((await getLifeProfile("other@example.com", db)).facts.length, 0);
    for (let i = 0; i < 35; i++) await rememberLifeFact(owner, { ...args, key: `fact_${i}` }, db);
    memory = await getLifeProfile(owner, db);
    assert.equal(compactLifeMemory(memory).facts.length, 36, "All confirmed facts survive; no obsolete 30-fact cap");
    assert.match(lifeMemoryPrompt(memory), /Always use emojis/);
    assert.equal(memory.facts.some(fact => fact.kind === "custom_instructions"), false);
    await updateLifeProfile(owner, { goals: ["money"] }, "settings", db);
    assert.match((await getLifeProfile(owner, db)).profile!.customInstructions, /professional/);
    await updateLifeProfile(owner, { customInstructions: null }, "settings", db);
    assert.equal((await getLifeProfile(owner, db)).profile!.customInstructions, "");
    const person = { name: "Max", role: "Brother", email: "max@example.com", phone: "+1 416 555 0123" };
    await saveLifePerson(owner, person, undefined, db);
    await saveLifePerson(owner, { ...person, role: "Accountant", email: "max.work@example.com" }, undefined, db);
    memory = await getLifeProfile(owner, db);
    const people = memory.facts.filter(fact => fact.kind === "person");
    assert.equal(people.length, 2, "People with the same name must not overwrite each other");
    const brother = people.find(fact => fact.value.role === "Brother")!;
    assert.equal(await saveLifePerson("other@example.com", { ...person, email: "wrong@example.com" }, brother.id, db), false);
    assert.equal(await saveLifePerson(owner, person, memory.facts.find(fact => fact.kind === "preference")!.id, db), false, "Person editing cannot overwrite ordinary memories");
    assert.equal(await saveLifePerson(owner, { ...person, phone: "", email: "max.new@example.com" }, brother.id, db), true);
    memory = await getLifeProfile(owner, db);
    assert.equal(compactLifeMemory(memory).facts.length, 37, "The newly saved focus preference is retained too");
    assert.equal(compactLifeMemory(memory).people.length, 2, "People remain available alongside every confirmed fact");
    assert.equal(compactLifeMemory(memory).people.find(item => item.id === brother.id)!.email, "max.new@example.com");
    assert.equal(compactLifeMemory(memory).people.find(item => item.id === brother.id)!.phone, "");
    assert.equal(await deleteLifeFact("other@example.com", brother.id, db), false);
    assert.equal(await deleteLifeFact(owner, brother.id, db), true);
    assert.equal(compactLifeMemory(await getLifeProfile(owner, db)).people.length, 1);
    assert.equal(await saveLifePerson(owner, person, brother.id, db), false, "A stale editor must not resurrect a deleted person");
    memory = await getLifeProfile(owner, db);
    assert.equal(await deleteLifeFact(owner, memory.facts[0].id, db), true);
    assert.equal((await getLifeProfile(owner, db)).facts.some(fact => fact.id === memory.facts[0].id), false);

    // Exercise the same tool the agent calls, then read through the Settings API's loader.
    const store = new MemoryRunStore();
    const request = "Remember Jordan is my dentist, jordan@example.com, +1 416 555 0198.";
    const run = await store.createRun({ userId: owner, request, title: "Remember Jordan", category: "other", decisionId: null, metadata: {} });
    const remember = createRememberTool({ userId: owner, runId: run.id, store }, undefined, (email, args) => rememberLifePerson(email, args, db));
    const options = { toolCallId: "person-memory", messages: [], context: {} };
    const create = { key: "jordan_dentist", category: "person" as const, content: "Jordan is my dentist", quote: request,
      person: { operation: "save" as const, id: null, name: "Jordan", role: "Dentist", email: "jordan@example.com", phone: "+1 416 555 0198" } };
    await remember.execute!(create, options);
    await remember.execute!(create, options);
    const savedPeople = (await getLifeProfile(owner, db)).facts.filter(fact => fact.kind === "person");
    assert.equal(savedPeople.filter(fact => fact.value.name === "Jordan").length, 1, "A repeated creation is idempotent");
    const jordan = savedPeople.find(fact => fact.value.name === "Jordan")!;
    assert.equal(jordan.source, "conversation");
    assert.equal(jordan.evidence.quote, request);
    await assert.rejects(async () => remember.execute!({ ...create, person: { ...create.person, name: "Different person" } }, options), /key already exists/);
    const correction = "Change Jordan's email to jordan.new@example.com.";
    await store.appendMessages(run.id, [{ role: "user", content: correction }]);
    const update = { ...create, quote: correction, person: { operation: "save" as const, id: jordan.id, name: null, role: null, email: "jordan.new@example.com", phone: null } };
    await remember.execute!(update, options);
    let updated = compactLifeMemory(await getLifeProfile(owner, db)).people.find(person => person.id === jordan.id)!;
    assert.deepEqual(updated, { id: jordan.id, name: "Jordan", role: "Dentist", email: "jordan.new@example.com", phone: "+1 416 555 0198" });
    await assert.rejects(() => rememberLifePerson("other@example.com", { ...update, sourceRunId: run.id }, db), /not found/);
    const clear = "Remove Jordan's phone number.";
    await store.appendMessages(run.id, [{ role: "user", content: clear }]);
    await remember.execute!({ ...update, quote: clear, person: { ...update.person, email: null, phone: "" } }, options);
    updated = compactLifeMemory(await getLifeProfile(owner, db)).people.find(person => person.id === jordan.id)!;
    assert.equal(updated.phone, "");
    assert.equal(updated.email, "jordan.new@example.com");
    const remove = "Forget Jordan from my saved people.";
    await store.appendMessages(run.id, [{ role: "user", content: remove }]);
    const deletion = { ...update, quote: remove, person: { ...update.person, operation: "remove" as const, email: null } };
    await assert.rejects(() => rememberLifePerson("other@example.com", { ...deletion, sourceRunId: run.id }, db), /not found/);
    await assert.rejects(async () => remember.execute!({ ...deletion, person: { ...deletion.person, id: null } }, options), /requires their saved person ID/);
    await remember.execute!(deletion, options);
    assert.equal(compactLifeMemory(await getLifeProfile(owner, db)).people.some(person => person.id === jordan.id), false);
    assert.equal((await getLifeProfile(owner, db)).facts.some(fact => fact.id === jordan.id), false);
  } finally { await client.end(); await admin.unsafe(`drop schema ${name} cascade`); await admin.end(); }
});

test("saved people validate contact details without requiring both email and phone", () => {
  const person = { name: " Max ", role: "Brother", email: "max@example.com", phone: "+1 (416) 555-0123" };
  assert.equal(personMemorySchema.parse(person).name, "Max");
  assert.equal(personMemorySchema.safeParse({ ...person, email: "", phone: "" }).success, true);
  assert.equal(personMemorySchema.safeParse({ ...person, name: " " }).success, false);
  assert.equal(personMemorySchema.safeParse({ ...person, email: "not-an-email" }).success, false);
  assert.equal(personMemorySchema.safeParse({ ...person, phone: "call him sometime" }).success, false);
  assert.doesNotMatch(JSON.stringify(z.toJSONSchema(rememberSchema)), /\(\?[=!<]/, "The memory tool schema must not emit unsupported regex lookarounds");
});
