import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { getCloudBrowser, closeCloudBrowser } from "../lib/harness/browser/registry";
import { resolveBrowserTarget, type BrowserTarget } from "../lib/harness/browser/policy";

const { url } = JSON.parse(readFileSync("artifacts/browser-capabilities/fixture.json", "utf8"));
const owner = `capabilities-${crypto.randomUUID()}@example.invalid`;
const browser = getCloudBrowser(owner);
const root = "artifacts/browser-capabilities";
mkdirSync(root, { recursive: true });
const checks: string[] = [];
const secondary = { role: "region", name: "Secondary" };
const search = { role: "button", name: "Search", within: secondary };
const query = { role: "searchbox", name: "Query", within: secondary };
try {
  let page = await browser.open(owner, url);
  writeFileSync(`${root}/cloud-initial.json`, JSON.stringify(page, null, 2));
  const target = (value: BrowserTarget) => resolveBrowserTarget(value, page);
  assert.throws(() => target({ role: "button", name: "Search" }), /2 controls/);
  checks.push("unscoped duplicate rejected");
  page = await browser.type(target(query), "violet");
  page = await browser.click(target(search));
  assert.match(page.text, /Secondary result: violet/);
  assert.match(page.text, /Primary untouched/);
  checks.push("scoped click changed only Secondary");
  const inspected = await browser.inspect(target(secondary));
  assert.match(inspected.text, /Secondary result: violet/);
  assert.doesNotMatch(inspected.text, /Primary untouched/);
  checks.push("targeted inspection excludes other region");
  writeFileSync(`${root}/cloud-targeted.json`, JSON.stringify(inspected, null, 2));
  page = await browser.type(target(query), "amber");
  page = await browser.press(target(query), "Enter");
  assert.match(page.text, /Secondary result: amber/);
  checks.push("focused Enter submits exact form");
  page = await browser.press(target(query), "ControlOrMeta+A");
  page = await browser.press(target(query), "Backspace");
  assert.equal(page.elements.find(e => e.ref === target(query))?.value, "");
  checks.push("selection shortcut and editing key");
  page = await browser.click(target({ role: "button", name: "Start loading" }));
  page = await browser.waitFor({ role: "button", name: "Loaded result" }, "enabled", 5000);
  assert.equal(page.elements.find(e => e.name === "Loaded result")?.disabled, false);
  checks.push("condition wait waits for enabled control");
  page = await browser.click(target({ role: "button", name: "Hide result" }));
  page = await browser.waitFor({ role: "button", name: "Loaded result" }, "hidden", 1000);
  assert.ok(!page.elements.some(e => e.name === "Loaded result"));
  checks.push("condition wait for hidden/absent control");
  await assert.rejects(browser.waitFor({ role: "button", name: "Never appears" }, "visible", 300), /timed out/);
  checks.push("unsatisfied wait fails explicitly");
  page = await browser.hover(target({ role: "button", name: "Details" }));
  assert.match(page.text, /Hover detail: violet 73/);
  checks.push("hover reveals tooltip");
  page = await browser.scroll(1000, target({ role: "region", name: "Scrollable panel" }));
  assert.match(page.text, /Panel scroll position: [1-9]/);
  assert.match(page.text, /Sent count: 0/);
  checks.push("panel scroll and no external fixture action");
  writeFileSync(`${root}/cloud-final.json`, JSON.stringify(page, null, 2));
  writeFileSync(`${root}/cloud-final.png`, await browser.screenshot());
  writeFileSync(`${root}/cloud-checks.json`, JSON.stringify({ passed: true, checks }, null, 2));
  console.log(JSON.stringify({ passed: true, checks }));
} finally {
  await closeCloudBrowser(owner);
}
