"use client";
import { SUPPORT_EMAIL } from "../../lib/deployment";

import {useState,useRef} from 'react';
import Link from 'next/link';
import styles from './waitlist.module.css';
import glossy from '../glossy-button.module.css';
import {Mascot} from '../task-icon';
export default function WaitlistForm(){const[email,setEmail]=useState('');const[busy,setBusy]=useState(false);const[joined,setJoined]=useState(false);const[error,setError]=useState('');const inFlight=useRef(false);
 return <main className={styles.page}><Link href="/" className={styles.back} aria-label="Back to Dash"><Mascot size={26} eyeColor="#fff"/><span>Dash</span></Link><div className={styles.content}>{joined?<section role="status"><h1>You’re on the list.</h1><p>We’ll email you when your spot is ready.</p><Link className={`${styles.home} ${glossy.button}`} href="/">Back to Dash <span aria-hidden="true">→</span></Link></section>:<form onSubmit={async event=>{event.preventDefault();if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{const response=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await response.json();if(!response.ok)throw new Error(data.error??'Couldn’t join. Please try again.');setJoined(true);}catch(caught){setError(caught instanceof Error?caught.message:'Couldn’t join. Please try again.');}finally{inFlight.current=false;setBusy(false);}}}><h1>Join the Dash waitlist.</h1><p>Your assistant. Less on your plate.<br/>We’re inviting people in small batches.</p><label className={styles.label} htmlFor="waitlist-email">Email address</label><input id="waitlist-email" name="email" type="email" autoComplete="email" inputMode="email" autoCapitalize="none" spellCheck={false} placeholder="you@example.com" maxLength={254} required value={email} onChange={event=>setEmail(event.target.value)} disabled={busy}/><p className={styles.note}>We’ll only email you about access to Dash.</p>{error&&<p className={styles.error} role="alert">{error}</p>}<button className={glossy.button} type="submit" disabled={busy}>{busy?'Joining…':'Join the waitlist'}<span aria-hidden="true">→</span></button></form>}</div><nav className={styles.legal} aria-label="Legal"><Link href="/privacy">Privacy</Link><span aria-hidden="true">·</span><Link href="/terms">Terms</Link><span aria-hidden="true">·</span><a href={`mailto:${SUPPORT_EMAIL}`}>Contact</a></nav></main>;
}
